# Second stage: Run tests
FROM elixir:1.15.4-alpine as test_stage

ENV LANG=C.UTF-8
ENV MIX_ENV="test"

# Set the working directory
WORKDIR /app

# Install inotify-tools for live-reload during development
RUN apk add --no-cache inotify-tools build-base npm

# Install Hex and Rebar
RUN mix local.hex --force && mix local.rebar --force

# Copy mix.exs and mix.lock to the container
COPY mix.exs mix.lock ./

# Install dependencies for tests
RUN mix deps.get

# Compile the dependencies
RUN mix deps.compile

# Copy remaining application code to the container
COPY . .

# Run tests
CMD ["mix", "test"]