defmodule ThreatShield.Const.Locations do
  alias ThreatShield.Const.Locations

  import ThreatShieldWeb.Gettext

  def predefined_locations() do
    [
      %{iso_code: "AD", flag: "🇦🇩", name: dgettext("organisation", "Andorra")},
      %{iso_code: "AE", flag: "🇦🇪", name: dgettext("organisation", "United Arab Emirates")},
      %{iso_code: "AF", flag: "🇦🇫", name: dgettext("organisation", "Afghanistan")},
      %{iso_code: "AG", flag: "🇦🇬", name: dgettext("organisation", "Antigua and Barbuda")},
      %{iso_code: "AI", flag: "🇦🇮", name: dgettext("organisation", "Anguilla")},
      %{iso_code: "AL", flag: "🇦🇱", name: dgettext("organisation", "Albania")},
      %{iso_code: "AM", flag: "🇦🇲", name: dgettext("organisation", "Armenia")},
      %{iso_code: "AO", flag: "🇦🇴", name: dgettext("organisation", "Angola")},
      %{iso_code: "AQ", flag: "🇦🇶", name: dgettext("organisation", "Antarctica")},
      %{iso_code: "AR", flag: "🇦🇷", name: dgettext("organisation", "Argentina")},
      %{iso_code: "AS", flag: "🇦🇸", name: dgettext("organisation", "American Samoa")},
      %{iso_code: "AT", flag: "🇦🇹", name: dgettext("organisation", "Austria")},
      %{iso_code: "AU", flag: "🇦🇺", name: dgettext("organisation", "Australia")},
      %{iso_code: "AW", flag: "🇦🇼", name: dgettext("organisation", "Aruba")},
      %{iso_code: "AX", flag: "🇦🇽", name: dgettext("organisation", "Åland Islands")},
      %{iso_code: "AZ", flag: "🇦🇿", name: dgettext("organisation", "Azerbaijan")},
      %{iso_code: "BA", flag: "🇧🇦", name: dgettext("organisation", "Bosnia and Herzegovina")},
      %{iso_code: "BB", flag: "🇧🇧", name: dgettext("organisation", "Barbados")},
      %{iso_code: "BD", flag: "🇧🇩", name: dgettext("organisation", "Bangladesh")},
      %{iso_code: "BE", flag: "🇧🇪", name: dgettext("organisation", "Belgium")},
      %{iso_code: "BF", flag: "🇧🇫", name: dgettext("organisation", "Burkina Faso")},
      %{iso_code: "BG", flag: "🇧🇬", name: dgettext("organisation", "Bulgaria")},
      %{iso_code: "BH", flag: "🇧🇭", name: dgettext("organisation", "Bahrain")},
      %{iso_code: "BI", flag: "🇧🇮", name: dgettext("organisation", "Burundi")},
      %{iso_code: "BJ", flag: "🇧🇯", name: dgettext("organisation", "Benin")},
      %{iso_code: "BL", flag: "🇧🇱", name: dgettext("organisation", "Saint Barthélemy")},
      %{iso_code: "BM", flag: "🇧🇲", name: dgettext("organisation", "Bermuda")},
      %{iso_code: "BN", flag: "🇧🇳", name: dgettext("organisation", "Brunei Darussalam")},
      %{iso_code: "BO", flag: "🇧🇴", name: dgettext("organisation", "Bolivia")},
      %{
        iso_code: "BQ",
        flag: "🇧🇶",
        name: dgettext("organisation", "Bonaire, Sint Eustatius and Saba")
      },
      %{iso_code: "BR", flag: "🇧🇷", name: dgettext("organisation", "Brazil")},
      %{iso_code: "BS", flag: "🇧🇸", name: dgettext("organisation", "Bahamas")},
      %{iso_code: "BT", flag: "🇧🇹", name: dgettext("organisation", "Bhutan")},
      %{iso_code: "BV", flag: "🇧🇻", name: dgettext("organisation", "Bouvet Island")},
      %{iso_code: "BW", flag: "🇧🇼", name: dgettext("organisation", "Botswana")},
      %{iso_code: "BY", flag: "🇧🇾", name: dgettext("organisation", "Belarus")},
      %{iso_code: "BZ", flag: "🇧🇿", name: dgettext("organisation", "Belize")},
      %{iso_code: "CA", flag: "🇨🇦", name: dgettext("organisation", "Canada")},
      %{iso_code: "CC", flag: "🇨🇨", name: dgettext("organisation", "Cocos (Keeling) Islands")},
      %{
        iso_code: "CD",
        flag: "🇨🇩",
        name: dgettext("organisation", "Congo, Democratic Republic of the")
      },
      %{iso_code: "CF", flag: "🇨🇫", name: dgettext("organisation", "Central African Republic")},
      %{iso_code: "CG", flag: "🇨🇬", name: dgettext("organisation", "Congo")},
      %{iso_code: "CH", flag: "🇨🇭", name: dgettext("organisation", "Switzerland")},
      %{iso_code: "CI", flag: "🇨🇮", name: dgettext("organisation", "Côte d'Ivoire")},
      %{iso_code: "CK", flag: "🇨🇰", name: dgettext("organisation", "Cook Islands")},
      %{iso_code: "CL", flag: "🇨🇱", name: dgettext("organisation", "Chile")},
      %{iso_code: "CM", flag: "🇨🇲", name: dgettext("organisation", "Cameroon")},
      %{iso_code: "CN", flag: "🇨🇳", name: dgettext("organisation", "China")},
      %{iso_code: "CO", flag: "🇨🇴", name: dgettext("organisation", "Colombia")},
      %{iso_code: "CR", flag: "🇨🇷", name: dgettext("organisation", "Costa Rica")},
      %{iso_code: "CU", flag: "🇨🇺", name: dgettext("organisation", "Cuba")},
      %{iso_code: "CV", flag: "🇨🇻", name: dgettext("organisation", "Cabo Verde")},
      %{iso_code: "CW", flag: "🇨🇼", name: dgettext("organisation", "Curaçao")},
      %{iso_code: "CX", flag: "🇨🇽", name: dgettext("organisation", "Christmas Island")},
      %{iso_code: "CY", flag: "🇨🇾", name: dgettext("organisation", "Cyprus")},
      %{iso_code: "CZ", flag: "🇨🇿", name: dgettext("organisation", "Czech Republic")},
      %{iso_code: "DE", flag: "🇩🇪", name: dgettext("organisation", "Germany")},
      %{iso_code: "DJ", flag: "🇩🇯", name: dgettext("organisation", "Djibouti")},
      %{iso_code: "DK", flag: "🇩🇰", name: dgettext("organisation", "Denmark")},
      %{iso_code: "DM", flag: "🇩🇲", name: dgettext("organisation", "Dominica")},
      %{iso_code: "DO", flag: "🇩🇴", name: dgettext("organisation", "Dominican Republic")},
      %{iso_code: "DZ", flag: "🇩🇿", name: dgettext("organisation", "Algeria")},
      %{iso_code: "EC", flag: "🇪🇨", name: dgettext("organisation", "Ecuador")},
      %{iso_code: "EE", flag: "🇪🇪", name: dgettext("organisation", "Estonia")},
      %{iso_code: "EG", flag: "🇪🇬", name: dgettext("organisation", "Egypt")},
      %{iso_code: "EH", flag: "🇪🇭", name: dgettext("organisation", "Western Sahara")},
      %{iso_code: "ER", flag: "🇪🇷", name: dgettext("organisation", "Eritrea")},
      %{iso_code: "ES", flag: "🇪🇸", name: dgettext("organisation", "Spain")},
      %{iso_code: "ET", flag: "🇪🇹", name: dgettext("organisation", "Ethiopia")},
      %{iso_code: "FI", flag: "🇫🇮", name: dgettext("organisation", "Finland")},
      %{iso_code: "FJ", flag: "🇫🇯", name: dgettext("organisation", "Fiji")},
      %{iso_code: "FK", flag: "🇫🇰", name: dgettext("organisation", "Falkland Islands (Malvinas)")},
      %{
        iso_code: "FM",
        flag: "🇫🇲",
        name: dgettext("organisation", "Micronesia, Federated States of")
      },
      %{iso_code: "FO", flag: "🇫🇴", name: dgettext("organisation", "Faroe Islands")},
      %{iso_code: "FR", flag: "🇫🇷", name: dgettext("organisation", "France")},
      %{iso_code: "GA", flag: "🇬🇦", name: dgettext("organisation", "Gabon")},
      %{iso_code: "GB", flag: "🇬🇧", name: dgettext("organisation", "United Kingdom")},
      %{iso_code: "GD", flag: "🇬🇩", name: dgettext("organisation", "Grenada")},
      %{iso_code: "GE", flag: "🇬🇪", name: dgettext("organisation", "Georgia")},
      %{iso_code: "GF", flag: "🇬🇫", name: dgettext("organisation", "French Guiana")},
      %{iso_code: "GG", flag: "🇬🇬", name: dgettext("organisation", "Guernsey")},
      %{iso_code: "GH", flag: "🇬🇭", name: dgettext("organisation", "Ghana")},
      %{iso_code: "GI", flag: "🇬🇮", name: dgettext("organisation", "Gibraltar")},
      %{iso_code: "GL", flag: "🇬🇱", name: dgettext("organisation", "Greenland")},
      %{iso_code: "GM", flag: "🇬🇲", name: dgettext("organisation", "Gambia")},
      %{iso_code: "GN", flag: "🇬🇳", name: dgettext("organisation", "Guinea")},
      %{iso_code: "GP", flag: "🇬🇵", name: dgettext("organisation", "Guadeloupe")},
      %{iso_code: "GQ", flag: "🇬🇶", name: dgettext("organisation", "Equatorial Guinea")},
      %{iso_code: "GR", flag: "🇬🇷", name: dgettext("organisation", "Greece")},
      %{
        iso_code: "GS",
        flag: "🇬🇸",
        name: dgettext("organisation", "South Georgia and the South Sandwich Islands")
      },
      %{iso_code: "GT", flag: "🇬🇹", name: dgettext("organisation", "Guatemala")},
      %{iso_code: "GU", flag: "🇬🇺", name: dgettext("organisation", "Guam")},
      %{iso_code: "GW", flag: "🇬🇼", name: dgettext("organisation", "Guinea-Bissau")},
      %{iso_code: "GY", flag: "🇬🇾", name: dgettext("organisation", "Guyana")},
      %{iso_code: "HK", flag: "🇭🇰", name: dgettext("organisation", "Hong Kong")},
      %{
        iso_code: "HM",
        flag: "🇭🇲",
        name: dgettext("organisation", "Heard Island and McDonald Islands")
      },
      %{iso_code: "HN", flag: "🇭🇳", name: dgettext("organisation", "Honduras")},
      %{iso_code: "HR", flag: "🇭🇷", name: dgettext("organisation", "Croatia")},
      %{iso_code: "HT", flag: "🇭🇹", name: dgettext("organisation", "Haiti")},
      %{iso_code: "HU", flag: "🇭🇺", name: dgettext("organisation", "Hungary")},
      %{iso_code: "ID", flag: "🇮🇩", name: dgettext("organisation", "Indonesia")},
      %{iso_code: "IE", flag: "🇮🇪", name: dgettext("organisation", "Ireland")},
      %{iso_code: "IL", flag: "🇮🇱", name: dgettext("organisation", "Israel")},
      %{iso_code: "IM", flag: "🇮🇲", name: dgettext("organisation", "Isle of Man")},
      %{iso_code: "IN", flag: "🇮🇳", name: dgettext("organisation", "India")},
      %{
        iso_code: "IO",
        flag: "🇮🇴",
        name: dgettext("organisation", "British Indian Ocean Territory")
      },
      %{iso_code: "IQ", flag: "🇮🇶", name: dgettext("organisation", "Iraq")},
      %{iso_code: "IR", flag: "🇮🇷", name: dgettext("organisation", "Iran, Islamic Republic of")},
      %{iso_code: "IS", flag: "🇮🇸", name: dgettext("organisation", "Iceland")},
      %{iso_code: "IT", flag: "🇮🇹", name: dgettext("organisation", "Italy")},
      %{iso_code: "JE", flag: "🇯🇪", name: dgettext("organisation", "Jersey")},
      %{iso_code: "JM", flag: "🇯🇲", name: dgettext("organisation", "Jamaica")},
      %{iso_code: "JO", flag: "🇯🇴", name: dgettext("organisation", "Jordan")},
      %{iso_code: "JP", flag: "🇯🇵", name: dgettext("organisation", "Japan")},
      %{iso_code: "KE", flag: "🇰🇪", name: dgettext("organisation", "Kenya")},
      %{iso_code: "KG", flag: "🇰🇬", name: dgettext("organisation", "Kyrgyzstan")},
      %{iso_code: "KH", flag: "🇰🇭", name: dgettext("organisation", "Cambodia")},
      %{iso_code: "KI", flag: "🇰🇮", name: dgettext("organisation", "Kiribati")},
      %{iso_code: "KM", flag: "🇰🇲", name: dgettext("organisation", "Comoros")},
      %{iso_code: "KN", flag: "🇰🇳", name: dgettext("organisation", "Saint Kitts and Nevis")},
      %{
        iso_code: "KP",
        flag: "🇰🇵",
        name: dgettext("organisation", "Korea, Democratic People's Republic of")
      },
      %{iso_code: "KR", flag: "🇰🇷", name: dgettext("organisation", "Korea, Republic of")},
      %{iso_code: "KW", flag: "🇰🇼", name: dgettext("organisation", "Kuwait")},
      %{iso_code: "KY", flag: "🇰🇾", name: dgettext("organisation", "Cayman Islands")},
      %{iso_code: "KZ", flag: "🇰🇿", name: dgettext("organisation", "Kazakhstan")},
      %{
        iso_code: "LA",
        flag: "🇱🇦",
        name: dgettext("organisation", "Lao People's Democratic Republic")
      },
      %{iso_code: "LB", flag: "🇱🇧", name: dgettext("organisation", "Lebanon")},
      %{iso_code: "LC", flag: "🇱🇨", name: dgettext("organisation", "Saint Lucia")},
      %{iso_code: "LI", flag: "🇱🇮", name: dgettext("organisation", "Liechtenstein")},
      %{iso_code: "LK", flag: "🇱🇰", name: dgettext("organisation", "Sri Lanka")},
      %{iso_code: "LR", flag: "🇱🇷", name: dgettext("organisation", "Liberia")},
      %{iso_code: "LS", flag: "🇱🇸", name: dgettext("organisation", "Lesotho")},
      %{iso_code: "LT", flag: "🇱🇹", name: dgettext("organisation", "Lithuania")},
      %{iso_code: "LU", flag: "🇱🇺", name: dgettext("organisation", "Luxembourg")},
      %{iso_code: "LV", flag: "🇱🇻", name: dgettext("organisation", "Latvia")},
      %{iso_code: "LY", flag: "🇱🇾", name: dgettext("organisation", "Libya")},
      %{iso_code: "MA", flag: "🇲🇦", name: dgettext("organisation", "Morocco")},
      %{iso_code: "MC", flag: "🇲🇨", name: dgettext("organisation", "Monaco")},
      %{iso_code: "MD", flag: "🇲🇩", name: dgettext("organisation", "Moldova, Republic of")},
      %{iso_code: "ME", flag: "🇲🇪", name: dgettext("organisation", "Montenegro")},
      %{iso_code: "MF", flag: "🇲🇫", name: dgettext("organisation", "Saint Martin (French part)")},
      %{iso_code: "MG", flag: "🇲🇬", name: dgettext("organisation", "Madagascar")},
      %{iso_code: "MH", flag: "🇲🇭", name: dgettext("organisation", "Marshall Islands")},
      %{iso_code: "MK", flag: "🇲🇰", name: dgettext("organisation", "North Macedonia")},
      %{iso_code: "ML", flag: "🇲🇱", name: dgettext("organisation", "Mali")},
      %{iso_code: "MM", flag: "🇲🇲", name: dgettext("organisation", "Myanmar")},
      %{iso_code: "MN", flag: "🇲🇳", name: dgettext("organisation", "Mongolia")},
      %{iso_code: "MO", flag: "🇲🇴", name: dgettext("organisation", "Macao")},
      %{iso_code: "MP", flag: "🇲🇵", name: dgettext("organisation", "Northern Mariana Islands")},
      %{iso_code: "MQ", flag: "🇲🇶", name: dgettext("organisation", "Martinique")},
      %{iso_code: "MR", flag: "🇲🇷", name: dgettext("organisation", "Mauritania")},
      %{iso_code: "MS", flag: "🇲🇸", name: dgettext("organisation", "Montserrat")},
      %{iso_code: "MT", flag: "🇲🇹", name: dgettext("organisation", "Malta")},
      %{iso_code: "MU", flag: "🇲🇺", name: dgettext("organisation", "Mauritius")},
      %{iso_code: "MV", flag: "🇲🇻", name: dgettext("organisation", "Maldives")},
      %{iso_code: "MW", flag: "🇲🇼", name: dgettext("organisation", "Malawi")},
      %{iso_code: "MX", flag: "🇲🇽", name: dgettext("organisation", "Mexico")},
      %{iso_code: "MY", flag: "🇲🇾", name: dgettext("organisation", "Malaysia")},
      %{iso_code: "MZ", flag: "🇲🇿", name: dgettext("organisation", "Mozambique")},
      %{iso_code: "NA", flag: "🇳🇦", name: dgettext("organisation", "Namibia")},
      %{iso_code: "NC", flag: "🇳🇨", name: dgettext("organisation", "New Caledonia")},
      %{iso_code: "NE", flag: "🇳🇪", name: dgettext("organisation", "Niger")},
      %{iso_code: "NF", flag: "🇳🇫", name: dgettext("organisation", "Norfolk Island")},
      %{iso_code: "NG", flag: "🇳🇬", name: dgettext("organisation", "Nigeria")},
      %{iso_code: "NI", flag: "🇳🇮", name: dgettext("organisation", "Nicaragua")},
      %{iso_code: "NL", flag: "🇳🇱", name: dgettext("organisation", "Netherlands")},
      %{iso_code: "NO", flag: "🇳🇴", name: dgettext("organisation", "Norway")},
      %{iso_code: "NP", flag: "🇳🇵", name: dgettext("organisation", "Nepal")},
      %{iso_code: "NR", flag: "🇳🇷", name: dgettext("organisation", "Nauru")},
      %{iso_code: "NU", flag: "🇳🇺", name: dgettext("organisation", "Niue")},
      %{iso_code: "NZ", flag: "🇳🇿", name: dgettext("organisation", "New Zealand")},
      %{iso_code: "OM", flag: "🇴🇲", name: dgettext("organisation", "Oman")},
      %{iso_code: "PA", flag: "🇵🇦", name: dgettext("organisation", "Panama")},
      %{iso_code: "PE", flag: "🇵🇪", name: dgettext("organisation", "Peru")},
      %{iso_code: "PF", flag: "🇵🇫", name: dgettext("organisation", "French Polynesia")},
      %{iso_code: "PG", flag: "🇵🇬", name: dgettext("organisation", "Papua New Guinea")},
      %{iso_code: "PH", flag: "🇵🇭", name: dgettext("organisation", "Philippines")},
      %{iso_code: "PK", flag: "🇵🇰", name: dgettext("organisation", "Pakistan")},
      %{iso_code: "PL", flag: "🇵🇱", name: dgettext("organisation", "Poland")},
      %{iso_code: "PM", flag: "🇵🇲", name: dgettext("organisation", "Saint Pierre and Miquelon")},
      %{iso_code: "PN", flag: "🇵🇳", name: dgettext("organisation", "Pitcairn")},
      %{iso_code: "PR", flag: "🇵🇷", name: dgettext("organisation", "Puerto Rico")},
      %{iso_code: "PS", flag: "🇵🇸", name: dgettext("organisation", "Palestine, State of")},
      %{iso_code: "PT", flag: "🇵🇹", name: dgettext("organisation", "Portugal")},
      %{iso_code: "PW", flag: "🇵🇼", name: dgettext("organisation", "Palau")},
      %{iso_code: "PY", flag: "🇵🇾", name: dgettext("organisation", "Paraguay")},
      %{iso_code: "QA", flag: "🇶🇦", name: dgettext("organisation", "Qatar")},
      %{iso_code: "RE", flag: "🇷🇪", name: dgettext("organisation", "Réunion")},
      %{iso_code: "RO", flag: "🇷🇴", name: dgettext("organisation", "Romania")},
      %{iso_code: "RS", flag: "🇷🇸", name: dgettext("organisation", "Serbia")},
      %{iso_code: "RU", flag: "🇷🇺", name: dgettext("organisation", "Russia")},
      %{iso_code: "RW", flag: "🇷🇼", name: dgettext("organisation", "Rwanda")},
      %{iso_code: "SA", flag: "🇸🇦", name: dgettext("organisation", "Saudi Arabia")},
      %{iso_code: "SB", flag: "🇸🇧", name: dgettext("organisation", "Solomon Islands")},
      %{iso_code: "SC", flag: "🇸🇨", name: dgettext("organisation", "Seychelles")},
      %{iso_code: "SD", flag: "🇸🇩", name: dgettext("organisation", "Sudan")},
      %{iso_code: "SE", flag: "🇸🇪", name: dgettext("organisation", "Sweden")},
      %{iso_code: "SG", flag: "🇸🇬", name: dgettext("organisation", "Singapore")},
      %{
        iso_code: "SH",
        flag: "🇸🇭",
        name: dgettext("organisation", "Saint Helena, Ascension and Tristan da Cunha")
      },
      %{iso_code: "SI", flag: "🇸🇮", name: dgettext("organisation", "Slovenia")},
      %{iso_code: "SJ", flag: "🇸🇯", name: dgettext("organisation", "Svalbard and Jan Mayen")},
      %{iso_code: "SK", flag: "🇸🇰", name: dgettext("organisation", "Slovakia")},
      %{iso_code: "SL", flag: "🇸🇱", name: dgettext("organisation", "Sierra Leone")},
      %{iso_code: "SM", flag: "🇸🇲", name: dgettext("organisation", "San Marino")},
      %{iso_code: "SN", flag: "🇸🇳", name: dgettext("organisation", "Senegal")},
      %{iso_code: "SO", flag: "🇸🇴", name: dgettext("organisation", "Somalia")},
      %{iso_code: "SR", flag: "🇸🇷", name: dgettext("organisation", "Suriname")},
      %{iso_code: "SS", flag: "🇸🇸", name: dgettext("organisation", "South Sudan")},
      %{iso_code: "ST", flag: "🇸🇹", name: dgettext("organisation", "Sao Tome and Principe")},
      %{iso_code: "SV", flag: "🇸🇻", name: dgettext("organisation", "El Salvador")},
      %{iso_code: "SX", flag: "🇸🇽", name: dgettext("organisation", "Sint Maarten (Dutch part)")},
      %{iso_code: "SY", flag: "🇸🇾", name: dgettext("organisation", "Syrian Arab Republic")},
      %{iso_code: "SZ", flag: "🇸🇿", name: dgettext("organisation", "Eswatini")},
      %{iso_code: "TC", flag: "🇹🇨", name: dgettext("organisation", "Turks and Caicos Islands")},
      %{iso_code: "TD", flag: "🇹🇩", name: dgettext("organisation", "Chad")},
      %{iso_code: "TF", flag: "🇹🇫", name: dgettext("organisation", "French Southern Territories")},
      %{iso_code: "TG", flag: "🇹🇬", name: dgettext("organisation", "Togo")},
      %{iso_code: "TH", flag: "🇹🇭", name: dgettext("organisation", "Thailand")},
      %{iso_code: "TJ", flag: "🇹🇯", name: dgettext("organisation", "Tajikistan")},
      %{iso_code: "TK", flag: "🇹🇰", name: dgettext("organisation", "Tokelau")},
      %{iso_code: "TL", flag: "🇹🇱", name: dgettext("organisation", "Timor-Leste")},
      %{iso_code: "TM", flag: "🇹🇲", name: dgettext("organisation", "Turkmenistan")},
      %{iso_code: "TN", flag: "🇹🇳", name: dgettext("organisation", "Tunisia")},
      %{iso_code: "TO", flag: "🇹🇴", name: dgettext("organisation", "Tonga")},
      %{iso_code: "TR", flag: "🇹🇷", name: dgettext("organisation", "Turkey")},
      %{iso_code: "TT", flag: "🇹🇹", name: dgettext("organisation", "Trinidad and Tobago")},
      %{iso_code: "TV", flag: "🇹🇻", name: dgettext("organisation", "Tuvalu")},
      %{iso_code: "TW", flag: "🇹🇼", name: dgettext("organisation", "Taiwan, Province of China")},
      %{
        iso_code: "TZ",
        flag: "🇹🇿",
        name: dgettext("organisation", "Tanzania, United Republic of")
      },
      %{iso_code: "UA", flag: "🇺🇦", name: dgettext("organisation", "Ukraine")},
      %{iso_code: "UG", flag: "🇺🇬", name: dgettext("organisation", "Uganda")},
      %{
        iso_code: "UM",
        flag: "🇺🇲",
        name: dgettext("organisation", "United States Minor Outlying Islands")
      },
      %{iso_code: "US", flag: "🇺🇸", name: dgettext("organisation", "United States")},
      %{iso_code: "UY", flag: "🇺🇾", name: dgettext("organisation", "Uruguay")},
      %{iso_code: "UZ", flag: "🇺🇿", name: dgettext("organisation", "Uzbekistan")},
      %{
        iso_code: "VA",
        flag: "🇻🇦",
        name: dgettext("organisation", "Holy See (Vatican City State)")
      },
      %{
        iso_code: "VC",
        flag: "🇻🇨",
        name: dgettext("organisation", "Saint Vincent and the Grenadines")
      },
      %{
        iso_code: "VE",
        flag: "🇻🇪",
        name: dgettext("organisation", "Venezuela, Bolivarian Republic of")
      },
      %{iso_code: "VG", flag: "🇻🇬", name: dgettext("organisation", "Virgin Islands, British")},
      %{iso_code: "VI", flag: "🇻🇮", name: dgettext("organisation", "Virgin Islands, U.S.")},
      %{iso_code: "VN", flag: "🇻🇳", name: dgettext("organisation", "Viet Nam")},
      %{iso_code: "VU", flag: "🇻🇺", name: dgettext("organisation", "Vanuatu")},
      %{iso_code: "WF", flag: "🇼🇫", name: dgettext("organisation", "Wallis and Futuna")},
      %{iso_code: "WS", flag: "🇼🇸", name: dgettext("organisation", "Samoa")},
      %{iso_code: "YE", flag: "🇾🇪", name: dgettext("organisation", "Yemen")},
      %{iso_code: "YT", flag: "🇾🇹", name: dgettext("organisation", "Mayotte")},
      %{iso_code: "ZA", flag: "🇿🇦", name: dgettext("organisation", "South Africa")},
      %{iso_code: "ZM", flag: "🇿🇲", name: dgettext("organisation", "Zambia")},
      %{iso_code: "ZW", flag: "🇿🇼", name: dgettext("organisation", "Zimbabwe")}
    ]
  end

  def list_locations() do
    Locations.predefined_locations()
    |> Enum.sort_by(& &1.name)
    |> Enum.reduce([{dgettext("organisation", "Please choose your country"), ""}], fn location,
                                                                                      acc ->
      [{"#{location.name} #{location.flag}", location.iso_code} | acc]
    end)
    |> Enum.reverse()
  end
end
